// Generated by tools/quake-pack.py — do not hand-edit.
// Frames are authored at 4x the logical draw height (see QUAKE_H in
// assets.js, which scales the blit down); ax/ay are in SOURCE px.
window.JH=window.JH||{};
window.JH.QUAKE_FRAMES={"sheet": "sprites/quake_walker/quake-frames.png", "frames": {"walk0": {"x": 2, "y": 0, "w": 202, "h": 256, "ax": 101.0, "ay": 256}, "walk1": {"x": 206, "y": 0, "w": 109, "h": 256, "ax": 54.5, "ay": 256}, "walk2": {"x": 317, "y": 0, "w": 76, "h": 256, "ax": 38.0, "ay": 256}, "walk3": {"x": 395, "y": 0, "w": 177, "h": 256, "ax": 88.5, "ay": 256}, "idle": {"x": 574, "y": 0, "w": 105, "h": 256, "ax": 52.5, "ay": 256}, "stompUp": {"x": 681, "y": 0, "w": 162, "h": 256, "ax": 81.0, "ay": 256}, "stompDown": {"x": 845, "y": 0, "w": 154, "h": 256, "ax": 77.0, "ay": 256}}, "scale": 4, "anims": {"walk": ["walk0", "walk1", "walk2", "walk3"]}};
