// Generated by tools/quake-pack.py — do not hand-edit.
// Frames are authored at 4x the logical draw height (see QUAKE_H in
// assets.js, which scales the blit down); ax/ay are in SOURCE px.
window.JH=window.JH||{};
window.JH.QUAKE_FRAMES={"sheet": "sprites/quake_walker/quake-frames.png", "frames": {"walk0": {"x": 2, "y": 0, "w": 132, "h": 256, "ax": 66.0, "ay": 256}, "walk1": {"x": 136, "y": 0, "w": 162, "h": 256, "ax": 81.0, "ay": 256}, "walk2": {"x": 300, "y": 0, "w": 115, "h": 256, "ax": 57.5, "ay": 256}, "walk3": {"x": 417, "y": 0, "w": 103, "h": 256, "ax": 51.5, "ay": 256}, "idle": {"x": 522, "y": 0, "w": 105, "h": 256, "ax": 52.5, "ay": 256}, "stompUp": {"x": 629, "y": 0, "w": 162, "h": 256, "ax": 81.0, "ay": 256}, "stompDown": {"x": 793, "y": 0, "w": 154, "h": 256, "ax": 77.0, "ay": 256}}, "scale": 4, "anims": {"walk": ["walk0", "walk1", "walk2", "walk3"]}, "stepFrames": [1, 3]};
