// Generated by tools/quake-pack.py — do not hand-edit.
// Frames are authored at 4x the logical draw height (see QUAKE_H in
// assets.js, which scales the blit down); ax/ay are in SOURCE px.
window.JH=window.JH||{};
window.JH.QUAKE_FRAMES={"sheet": "sprites/quake_walker/quake-frames.png", "frames": {"walk0": {"x": 2, "y": 0, "w": 147, "h": 256, "ax": 73.5, "ay": 256}, "walk1": {"x": 151, "y": 0, "w": 55, "h": 256, "ax": 27.5, "ay": 256}, "walk2": {"x": 208, "y": 0, "w": 150, "h": 256, "ax": 75.0, "ay": 256}, "walk3": {"x": 360, "y": 0, "w": 63, "h": 256, "ax": 31.5, "ay": 256}, "idle": {"x": 425, "y": 0, "w": 105, "h": 256, "ax": 52.5, "ay": 256}, "stompUp": {"x": 532, "y": 0, "w": 162, "h": 256, "ax": 81.0, "ay": 256}, "stompDown": {"x": 696, "y": 0, "w": 154, "h": 256, "ax": 77.0, "ay": 256}}, "scale": 4, "anims": {"walk": ["walk0", "walk1", "walk2", "walk3"]}};
