# Packs the normalized Quake Walker frames into one sprite sheet and emits the
# js/quake-frames.js metadata that indexes it.
#
# The old sheet was authored 1:1 against its 64px logical draw height, so at a
# 4x device scale it was UPSCALED while every other character (Jon 247px source
# for 53 logical, Ass Man 232 for 58) downscales cleanly. This packs at 4x
# instead; assets.js scales the blit down to QUAKE_H.
#
#   python tools/quake-pack.py
from PIL import Image
import json, os

SRC = "tmp/norm/quake"
# The four walk beats come from their own strip: a mirrored walk has near-
# identical SILHOUETTES by nature, so the alternation is carried by shading the
# FAR limbs darker. Both strips were normalised against their own idle at the
# same subject height (105 vs 106px wide), so they share a scale and splice
# without rescaling.
WALK_SRC = "tmp/norm/quakestomp"
# Two walk beats, not four. gpt-image-2 will not mirror near/far legs in a
# side profile — asked twice, both times the two "contact" poses came back
# ~8-15% apart while contact-vs-passing measured 61-64%. So the honest cycle is
# the two poses it CAN draw. Same conclusion as the collie trot.
ORDER = [("walk0", "walk0", WALK_SRC), ("walk1", "walk1", WALK_SRC),
         ("walk2", "walk2", WALK_SRC), ("walk3", "walk3", WALK_SRC),
         ("idle", "quake-k2", SRC),
         ("stompUp", "quake-k3", SRC), ("stompDown", "quake-k4", SRC)]
WALK = ["walk0", "walk1", "walk2", "walk3"]
# His walk IS a string of small stomps: frames 1 and 3 are the boot-slams.
# Declared here rather than hardcoded in entities.js so the shake stays tied to
# the art — reorder the cycle and this follows.
STEP_FRAMES = [1, 3]
OUT_PNG = "sprites/quake_walker/quake-frames.png"
OUT_JS = "js/quake-frames.js"

ims = [(name, Image.open(os.path.join(d, f + ".png")).convert("RGBA")) for name, f, d in ORDER]

# Trim each frame to its own content so the sheet isn't mostly empty, but keep
# every frame's FEET on the same bottom row — the anchor contract is ay = h.
trimmed = []
for name, im in ims:
    bb = im.getchannel("A").point(lambda a: 255 if a >= 16 else 0).getbbox()
    # keep full height (feet already sit on the canvas bottom), trim width only
    sub = im.crop((bb[0], 0, bb[2], im.height))
    trimmed.append((name, sub))

pad = 2
W = sum(s.width for _, s in trimmed) + pad * (len(trimmed) + 1)
H = max(s.height for _, s in trimmed)
sheet = Image.new("RGBA", (W, H), (0, 0, 0, 0))

frames = {}
x = pad
for name, sub in trimmed:
    sheet.paste(sub, (x, H - sub.height), sub)
    frames[name] = {
        "x": x, "y": 0, "w": sub.width, "h": H,
        # Anchor is the horizontal centre of the trimmed figure and its feet
        # row; assets.js scales both by QUAKE_H / h when it blits.
        "ax": round(sub.width / 2, 1), "ay": H,
    }
    x += sub.width + pad

sheet.save(OUT_PNG)
# SOURCE px per logical px. The blit must scale by THIS, not by frame height:
# the stomp wind-up raises both fists overhead, so its canvas is taller than
# the idle's, and scaling by canvas height would shrink every other pose to
# compensate. Frames are normalised so the IDLE subject is SRC_SCALE * the
# logical draw height; taller poses simply extend above the anchor.
SRC_SCALE = 4
data = {"sheet": "sprites/quake_walker/quake-frames.png", "frames": frames,
        "scale": SRC_SCALE, "anims": {"walk": WALK}, "stepFrames": STEP_FRAMES}
with open(OUT_JS, "w", encoding="utf-8") as f:
    f.write("// Generated by tools/quake-pack.py — do not hand-edit.\n")
    f.write("// Frames are authored at 4x the logical draw height (see QUAKE_H in\n")
    f.write("// assets.js, which scales the blit down); ax/ay are in SOURCE px.\n")
    f.write("window.JH=window.JH||{};\n")
    # window-qualified, not the bare `JH.` the original used: identical in a
    # browser, but this way node can require the atlas so tests can assert its
    # anchor contract.
    f.write("window.JH.QUAKE_FRAMES=" + json.dumps(data) + ";\n")
print(f"{OUT_PNG}  {sheet.size[0]}x{sheet.size[1]}")
for k, v in frames.items():
    print(f"  {k:10s} x={v['x']:4d} w={v['w']:3d} h={v['h']} ax={v['ax']}")
